### ISSUE TITLE
IE Error : SCRIPT1003: Expected ':'

### ISSUE THREAD

**Issue by akbeeram** [image-js/tiff#13]
I am trying to use this to count the number of pages in a tiff document. This works fine in Chrome & FF but IE gives an error. When I googled I found that the object notation should be proper({key: value}) for IE. The IE debugger points to this line:
const tags = {
    standard,
    exif,
    gps
};
Can this be changed to :
const tags = {
    standard: standard,
    exif: exif,
    gps: gps
};

**Comment by hipstersmoothie** [comment]
The README says that the library is written in ES6, so you'll need to transpile the source to make it work in older browsers.
