### ISSUE TITLE
Exception at PhotometricInterpretation=WhiteIsZero

### ISSUE THREAD

**Issue by mochi1212** [image-js/tiff#14]
If PhotometricInterpretation (262) is WhiteIsZero (0), an exception is raised at decodeImageData().
I want you to support WhiteIsZero.

**Comment by targos** [comment]
Hi, do you have an example image that can be used to reproduce this issue?

**Comment by mochi1212** [comment]
Please try this file.
https://drive.google.com/open?id=1OEdE4HN-qS_q7ruqVNRy6Q2Xb9qScZgS

**Comment by targos** [comment]
I have a fix ready. Can I keep your image in this repository for unit tests?
