### ISSUE TITLE
Unsupported lzw

### ISSUE THREAD

**Issue by dy** [image-js/tiff#15]
I am trying to decode this file [test_pattern.zip](https://github.com/image-js/tiff/files/2567193/test_pattern.zip)

```js
let {decode} = require('tiff')
decode(fs.readFileSync('./test_pattern.tiff'))
```

I get 
```sh
Error: Unsupported lzw: undefined
at unsupported (C:\projects\image-decode\node_modules\tiff\lib\index.js:870:10)
```

Not sure this error is valid.

**Comment by dy** [comment]
With this file [test_pattern.zip](https://github.com/image-js/tiff/files/2567208/test_pattern.zip)

I get

```sh
(node:10904) UnhandledPromiseRejectionWarning: Error: invalid compression: 8
    at TIFFDecoder.readStripData (C:\projects\image-decode\node_modules\tiff\lib\index.js:813:17)
```

**Comment by dy** [comment]
Also, that decodes this file:
[test_pattern.zip](https://github.com/image-js/tiff/files/2567267/test_pattern.zip)


Completely wrong:
![download](https://user-images.githubusercontent.com/300067/48283991-31cccf00-e42c-11e8-90a4-693219310e90.png)

**Comment by dy** [comment]
Tests do not seem to cover data validity right now.

**Comment by targos** [comment]
Yeah, the [readme](https://github.com/image-js/tiff#compatibility) mentions that we do not support compressed images yet. Thanks for the report and examples, though. I will not have time in the near future to work on it, but would be happy to review pull requests.

**Comment by dy** [comment]
Got you.
Well, I moved to [utif](https://ghub.io/utif) in [image-decode](https://ghub.io/image-decode) and pretty happy with that.
Possibly there is a sense to transition to _image-decode_ in _image.js_, I could transfer this repo to the org. (by coincidence I run [audiojs](https://github.com/audiojs) and state of affairs there is the same).

**Comment by targos** [comment]
LZW is now supported
