### ISSUE TITLE
would it be possible to add stack support ?

### ISSUE THREAD

**Issue by lpatiny** [image-js/tiff#17]
We need to make a kind of kinetic based on image analysis and the instrument generate a tiff containing a stack of pictures.

Would it be easy to add support for parsing such files ?

[stack.tif.zip](https://github.com/image-js/tiff/files/3814625/stack.tif.zip)

**Comment by targos** [comment]
what kind of error do you have with this file?

**Comment by targos** [comment]
I can indeed decode the file with the current version of the library. It returns 10 IFDs. Is it incorrect?

**Comment by lpatiny** [comment]
Yes this is correct. And there is a way to get those images as an array ?

**Comment by targos** [comment]
the `decode` method returns an array

**Comment by lpatiny** [comment]
@targos Great ! Many thanks it works perfectly !.
