### ISSUE TITLE
Add Float32 support for tiff Images.

### ISSUE THREAD

**Issue by Mforcen** [image-js/tiff#28]
It would be very nice if Float32 images could be used, since some scientific applications uses these kind of formats. For example, UAV Imagery.
I attach a photo in order to test the changes.
[float32.zip](https://github.com/image-js/tiff/files/6763638/float32.zip)

**Comment by Mforcen** [comment]
I'm opening this issue here since [targos](https://github.com/image-js/image-js/issues/558#issuecomment-873087775) told to me to do so, but I have been trying and it seems that the Float32 variable type is working.
I can load into browser and render it using plotty.

**Comment by targos** [comment]
Thanks for the test image. I added it in https://github.com/image-js/tiff/commit/59e8cccdd7870a7b39d7fdb588efe8f0a2c9b126. Let's continue the discussion in `image-js`, then.
