### ISSUE TITLE
How i can get an image from TiffIfd

### ISSUE THREAD

**Issue by VitalySkal** [image-js/tiff#30]
How I can get an image  from TiffIfd and then show it in browser?

**Comment by VitalySkal** [comment]
see getContext("2d")

**Comment by shamoon** [comment]
Any better answers out there than the above? Surprised there isnt a more straightforward example in the readme. I did see https://github.com/image-js/tiff/issues/45#issuecomment-1569764200 but that requires the image-js library, is that unavoidable?
