### ISSUE TITLE
Crash with RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by KatsuragiCSL** [image-js/tiff#43]
Cannot upload the tiff file here, hence here is the link to download the file which caused the crash: https://drive.google.com/file/d/1xF1Jwu33sIOc6EjgGnUge0KhgQ_ZzfFb/view?usp=sharing

Found by jsfuzz.

**Comment by lpatiny** [comment]
Is this file really 4.1 kb ? You can always zip a file to upload it in an issue.

I tried to check the file with imagemagick 'identify' and it gives also an error:

identify: crash-32003884646eeff421ef24f111cdd8c702c20028575569ec89600c2853a2033d.tiff: Can not read TIFF directory count. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/597.
identify: Failed to read directory at offset 309746. `TIFFReadDirectory' @ error/tiff.c/TIFFErrors/597.

Which application has generated this file and which application is able to open it ?

**Comment by KatsuragiCSL** [comment]
sorry for the mistake
