### ISSUE TITLE
Add option 'pages' that list 

### ISSUE THREAD

**Issue by lpatiny** [image-js/tiff#46]
By default we would parse all the images but we could as well have an option that is an array of pages to retrieve.

This would allow to get only the first images of a stack for example.

**Comment by opatiny** [comment]
What we want is to be able to pass an array of `number` as a parameter, which specifies the pages that we want to decode.

**Comment by opatiny** [comment]
Are you sure you want me to implement this feature? There is already the `firstImage` option, which allows to decode only the first image of the stack.
